# Del 1: För basic start, triggas när du vill i Github -> Actions -> Run workflow

# name: Basic Workflow

# on: [workflow_dispatch]

# jobs:
    # basic-workflow-job:
      #  runs-on: ubuntu-latest
       # steps:
        #    - name: Checkout repository
         #     uses: actions/checkout@v4
          #  - name: run a simple command (print a hello message)
           #   run: echo "Hello this is a simple workflow running on GitHub Actions!"



# ------------------------------------------------

# Del 2: För när workflow ska köras när push sker till repot

# name: Push workflow

# on: push

# jobs: 
  # push-workflow-job:
    # runs-on: windows-latest
    # steps: 
      # - name: Checkout repository
        # uses: actions/checkout@v4
      # - name: run a simple command
        # run: node --version && npm --version



# ------------------------------------------------



# Del 3: Push and build node.js

# name: Push and Build

# on: push

# jobs: 
  # build: 
    # runs-on: ubuntu-latest
    # steps: 
      # - name: Checkout repo
        # uses: actions/checkout@v4
      # - name: Set-up Node.JS
        # uses: actions/setup-node@v3
      # - name: Install dependencies
        # run: npm install
      # - name: Build project
        # run: npm run buildame: Set-up Node.JS
        # 

# ------------------------------------------------

# Del 3.1: Utökning av ovanstånde - Bygg flera nbode.js versioner med matrix strategi

# name: Push and Build

# on: push

# jobs: 
  # build: 
    # runs-on: ubuntu-latest
    # strategy:
      # matrix:
        # node-version: [16.x, 18.x, 20.x]
    # steps: 
      # - name: Checkout repo
        # uses: actions/checkout@v4
      # - name: Set-up Node.JS
        # uses: actions/setup-node@v3
        # with:
          # node-version: ${{ matrix.node-version }}
      # - name: Install dependencies
        # run: npm install
      # - name: Build project
        # run: npm run build

# ------------------------------------------------

# Del 4: 

name: Scheduler demo job

on: 
  workflow_dispatch:
  schedule: 
    - cron: '*/5 * * * *'

jobs: 
  scheduler-every-5-minute: 
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello my friend..."