# Del 1: För basic start, triggas när du vill i Github -> Actions -> Run workflow

# name: Basic Workflow

# on: [workflow_dispatch]

# jobs:
    # basic-workflow-job:
      #  runs-on: ubuntu-latest
       # steps:
        #    - name: Checkout repository
         #     uses: actions/checkout@v4
          #  - name: run a simple command (print a hello message)
           #   run: echo "Hello this is a simple workflow running on GitHub Actions!"



# ------------------------------------------------



# Del 2: För när workflow ska köras när push sker till repot

# name: Push workflow

# on: push

# jobs: 
  # push-workflow-job:
    # runs-on: windows-latest
    # steps: 
      # - name: Checkout repository
        # uses: actions/checkout@v4
      # - name: run a simple command
        # run: node --version && npm --version



# ------------------------------------------------



# Del 3: Push and build node.js

# name: Push and Build

# on: push

# jobs: 
  # build: 
    # runs-on: ubuntu-latest
    # steps: 
      # - name: Checkout repo
        # uses: actions/checkout@v4
      # - name: Set-up Node.JS
        # uses: actions/setup-node@v3
      # - name: Install dependencies
        # run: npm install
      # - name: Build project
        # run: npm run build



# ------------------------------------------------



# Del 3.1: Utökning av ovanstånde - Bygg flera nbode.js versioner med matrix strategi

# name: Push and Build

# on: push

# jobs: 
  # build: 
    # runs-on: ubuntu-latest
    # strategy:
      # matrix:
        # node-version: [16.x, 18.x, 20.x]
    # steps: 
      # - name: Checkout repo
        # uses: actions/checkout@v4
      # - name: Set-up Node.JS
        # uses: actions/setup-node@v3
        # with:
          # node-version: ${{ matrix.node-version }}
      # - name: Install dependencies
        # run: npm install
      # - name: Build project
        # run: npm run build



# ------------------------------------------------



# Del 4: Schemalägga kontroller, använd schedule tillsammans med cron formatet (cron = tidsangivelse)

# name: Scheduler demo job

# on: 
  # workflow_dispatch: # Denna del kan kommenteras ut när du har pushat första gången
  # schedule: 
    # - cron: '*/5 * * * *'

# jobs: 
  # scheduler-every-5-minute: 
    # runs-on: ubuntu-latest
    # steps:
      # - name: Print greeting
        # run: echo "Hello my friend..."



# ------------------------------------------------


# Del 5: Implementera ett workflow för att bygga och distribuera till GitHub Pages

name: Push, Build and Deploy

on: 
  push:
    branches: 
      - main

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node.JS
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build  
      - name: Skapa dummy-dist
        run: |
          mkdir -p dist
          echo "test" > dist/index.html
      - name: Upload dist as artifact
        uses: actions/upload-artifact@v4
        with: 
          name: dist-folder
          path: dist/
  deploy: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-folder
          path: dist
      - name: Deploy to Github pages
        uses: peaceiris/actions-gh-pages@v3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist


